version: "3.0"
services:
   laravel-web:
     depends_on:
       - laravel-db
     container_name: laravel-web
     image: bitnami/laravel:latest
     environment:
       - DB_HOST=laravel-db
       - DB_USERNAME=root
       - DB_DATABASE=sales_report
       - DB_PASSWORD=123456
     ports:
       - "8000:3000"
     networks:
       - laraveldev_net
     restart: always
     volumes:
       - D:\60160275\app:/app

   laravel-web:
     depends_on:
       - laravel-db
     container_name: laravel-account
     image: bitnami/laravel:latest
     environment:
       - DB_HOST=laravel-db
       - DB_USERNAME=root
       - DB_DATABASE=bank_account
       - DB_PASSWORD=123456
     ports:
       - "9000:3000"
     networks:
       - laraveldev_net
     restart: always
     volumes:
       - D:\60160275\app_account:/app

   laravel-db:
     container_name: laravel-db
     image: mysql:5.7
     environment:
       - MYSQL_ROOT_PASSWORD=123456
     networks:
       - laraveldev_net
     restart: always
     volumes:
       - D:\60160275\mysql:/var/lib/mysql
       - D:\60160275\data:/root

   laravel-phpmyadmin:
     container_name: laravel-phpmyadmin
     image: phpmyadmin/phpmyadmin
     environment:
       - PMA_HOST=laravel-db
     ports:
       - "8001:80"
     networks:
       - laraveldev_net
     restart: always

networks:
   laraveldev_net:
     driver: bridge

